/* ============================================
   حالة التطبيق وعناصر DOM
   ============================================ */

export const dom = {
  grid: document.getElementById('games-grid'),
  homeView: document.getElementById('home-view'),
  gameView: document.getElementById('game-view'),
  gameTitle: document.getElementById('game-title'),
  gameStatus: document.getElementById('game-status'),
  backBtn: document.getElementById('back-btn'),
  muteBtn: document.getElementById('mute-btn'),
  fullscreenBtn: document.getElementById('fullscreen-btn'),
  runnerContainer: document.getElementById('runner-container'),
  runnerCanvas: document.getElementById('runner-canvas'),
  runnerJumpBtn: document.getElementById('runner-jump'),
  runnerDuckBtn: document.getElementById('runner-duck'),
  tictactoeContainer: document.getElementById('tictactoe-container'),
  tictactoeBoard: document.getElementById('tictactoe-board'),
  tttReset: document.getElementById('ttt-reset'),
  archeryContainer: document.getElementById('archery-container'),
  archeryCanvas: document.getElementById('archery-canvas'),
  archeryStartBtn: document.getElementById('archery-start-btn'),
  archeryWaiting: document.getElementById('archery-waiting'),
  onlinePanel: document.getElementById('online-panel'),
  onlineBadge: document.getElementById('online-badge'),
  roomCodeDisplay: document.getElementById('room-code-display'),
  emojiPanel: document.getElementById('emoji-panel'),
  modeModal: document.getElementById('mode-modal'),
  modeGameName: document.getElementById('mode-game-name'),
  modeButtons: document.getElementById('mode-buttons'),
  onlineSetup: document.getElementById('online-setup'),
  onlineMsg: document.getElementById('online-msg'),
  roomInput: document.getElementById('room-input'),
  btnSingle: document.getElementById('btn-single'),
  btnOnline: document.getElementById('btn-online'),
  btnHost: document.getElementById('btn-host'),
  btnJoin: document.getElementById('btn-join'),
  modalCloses: document.querySelectorAll('.modal-close'),
  soonModal: document.getElementById('soon-modal'),
  confettiCanvas: document.getElementById('confetti-canvas')
};

export const state = {
  currentGame: null,
  soundMuted: false,
  peer: null,
  conn: null,
  isHost: false,
  mySymbol: null,
  roomCode: null,
  pendingGameId: null,
  ttt: {
    mode: 'single',
    board: Array(9).fill(null),
    turn: 'X',
    mySymbol: 'X',
    opponentSymbol: 'O',
    active: false,
    winner: null,
    winLine: []
  },
  runner: {
    active: false,
    over: false,
    score: 0,
    speed: 0,
    groundY: 0,
    player: null,
    obstacles: [],
    spawnTimer: 0,
    lastTime: 0,
    animId: null
  },
  archery: {
    active: false,
    over: false,
    mode: 'single',
    mySide: 'left',
    leftHealth: 100,
    rightHealth: 100,
    arrows: [],
    dragging: false,
    pointer: { x: 0, y: 0 },
    aimAngle: 0,
    animId: null,
    lastTime: 0,
    aiTimer: null
  }
};
